projects:
  tabian:
    schemaPath: ' ./graphql/schema.json'
    includes:
      - graphql/**.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: types/API.ts
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
